server:
  port: 8088
  servlet:
    context-path: /api/schoolresell/com/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schoolresell?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: 'MYSQL:202160940zhm'
    # 使用阿里巴巴的开源框架druid数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    # mysql 8.0.+使用的驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      #更新或者创建数据表结构
      ddl-auto: update
    show-sql: true